from core.constraints.fluidSolver import fluidSolver
from core.constraints.gasSolver import gasSolver
from core.constraints.shapeMatching import shapeMatchingSolver
from core.constraints.RegularContact import RegularContactSolver